### ISSUE TITLE
How to define different Enviorments

### ISSUE THREAD

**Issue by IeuanWalker** [AgustinBonilla/ConfigPlugin#2]
Sorry, this might sound stupid but at the moment everything defaults to dev.
How do I make a release build the prod configuration and a debug build the dev configuration etc?

**Comment by AgustinBonilla** [comment]
Hi, in the majority of my projects use two enviroments, dev/test and prod. To simplify this configuration use the DEBUG compilation directive, if you build on debug mode the app take the dev/test configurations and else if you build on release mode the app take the prod configurations.

public string CurrentConfiguration
        {
            get
            {
#if !DEBUG
                return "Prod";
#else
                return "Dev";
#endif
            }
        }

Other option is use custom compilation directives as in readme, this option is more complex than previously option.

Write me for any question.

Regards.
